apiVersion: v1
kind: Service
metadata:
  name: {{ include "kodecd.fullname" . }}-web
  labels:
    {{- include "kodecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "kodecd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
